spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/movies_db
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
security.api-key=dummy-api-key
jwt.secret=RzExeWVaMTFGbTRtUmVwSk1KOWxQOXdhWXlpM3lEWTZCQ1Y4d0tZNkREOWJaTWFITzY2RWlsc1l6T1dPWDdrVnUtampmSnBkeFVPN2hzVjBnTE42M3c9PQ==
jwt.expiration-ms=3600000
app.site.url=http://localhost:8080
b2.endpoint=https://s3.us-east-005.backblazeb2.com
b2.bucket=alimMovie
b2.key-id=005f7b2613097820000000001
b2.app-key=K005Umn3f9GPKRqVrn/J3OvPClH4wsI
b2.region=us-east-005
b2.url-validity-minutes=10080